Repository LangChain-OpenTutorial/LangChain-OpenTutorial, pull requests merged in 2025-05, with the labels that each got.

#882 [N-2] 09-Vector Store / 99-Master-Template
  09-VectorStore/99-Master-Template.ipynb
Labels: hot fix

#883 [N-2] 09-Vector Store / 05-Qdrant
  09-VectorStore/05-Qdrant.ipynb
  09-VectorStore/assets/05-qdrant-logo.png
  09-VectorStore/utils/qdrant/crud.py
  09-VectorStore/utils/qdrant/legacy/(legacy)05-Qdrant.ipynb
  09-VectorStore/utils/qdrant/legacy/qdrant.py
Labels: new tutorial suggestions

#885 [N-2] 09-VectorStore / 02-Chroma
  09-VectorStore/02-Chroma.ipynb
  09-VectorStore/utils/chroma/crud.py
Labels: hot fix

#886 [N-2] 09-VectorStore / 04-Pinecone
  09-VectorStore/04-Pinecone-Mulimodal.ipynb
  09-VectorStore/04-Pinecone.ipynb
  09-VectorStore/assets/04-pinecone-logo.png
  09-VectorStore/utils/pinecone/crud.py
  09-VectorStore/utils/pinecone/legacy/(legacy)04-Pinecone.ipynb
  09-VectorStore/utils/pinecone/legacy/pinecone.py
Labels: new tutorial suggestions

#470 [E-1] 17-LangGraph/01-Basic-LangGraph-Chatbot.ipynb
  17-LangGraph/01-Basic-LangGraph-Chatbot.ipynb
Labels: check plz

#811 [N-2] 07-TextSplitter / 05-CodeSplitter
  07-TextSplitter/05-CodeSplitter.ipynb
Labels: proofreading

#891 [Gitbook] uploading new contents
  docs/07-TextSplitter/03-TextSplittingMethods.md
  docs/07-TextSplitter/07-HTMLHeaderTextSplitter.md
  docs/09-VectorStore/03-Faiss.md
  docs/09-VectorStore/11-Faiss.md
  docs/09-VectorStore/99-Master-Template.md
  docs/09-VectorStore/img/04-pinecone-logo.png
  docs/09-VectorStore/img/05-qdrant-logo.png
  docs/17-LangGraph/01-Core-Features/02-LangGraph-ChatBot(groq).md
Labels: GitBook

#892 [Gitbook] Delete duplicate content
  docs/07-TextSplitter/03-TextSplittingMethods_.md
Labels: GitBook

#893 [Gitbook] Delete duplicate content
  docs/09-VectorStore/00-Template.md
  docs/09-VectorStore/00_Template.md
  docs/09-VectorStore/02-Chroma-Multimodal.md
  docs/09-VectorStore/02-ChromaWithLangchain.md
  docs/09-VectorStore/04-Pinecone-Mulimodal.md
  docs/12-RAG/03_RAG_Advanced.md
  docs/13-LangChain-Expression-Language/06-Configure.md
  docs/17-LangGraph/03-Use-Cases/05_LangGraph_Plan_and_Execute.md
Labels: GitBook
