Repository LangChain-OpenTutorial/LangChain-OpenTutorial, pull requests merged in 2025-01, with the labels that each got.

#28 LangSmith Tracking Setup
  01-BASIC/03-LangSmithTrackingSetup.ipynb
  01-BASIC/assets/03-langsmith-tracking-setup-01.png
  01-BASIC/assets/03-langsmith-tracking-setup-02.png
  01-BASIC/assets/03-langsmith-tracking-setup-03.png
  01-BASIC/assets/03-langsmith-tracking-setup-04.png
  01-BASIC/assets/03-langsmith-tracking-setup-05.png
  01-BASIC/assets/03-langsmith-tracking-setup-06.png
  01-BASIC/assets/03-langsmith-tracking-setup-07.png
  01-BASIC/assets/03-langsmith-tracking-setup-08.png
  poetry.lock
Labels: feature enhancement

#65 [N-3] 08-EMBEDDING / 06-LlamaCppEmbeddings
  08-EMBEDDING/06-LlamaCppEmbeddings.ipynb
Labels: feature enhancement, need correction

#20 [E-4] 05-MEMORY / 01-ConversationBufferMemory
  05-MEMORY/01-ConversationBufferMemory.ipynb
Labels: feature enhancement

#50 [N-1] 06-DocumentLoader / 08-TXT-Loader
  06-DocumentLoader/08-TXT-Loader.ipynb
  06-DocumentLoader/data/appendix-keywords-CP949.txt
  06-DocumentLoader/data/appendix-keywords-EUCKR.txt
  06-DocumentLoader/data/appendix-keywords-utf8.txt
  06-DocumentLoader/data/appendix-keywords.txt
Labels: request new tutorial

#31 [E-3] 04-MODEL / 06-HuggingFace Endpoints
  04-MODEL/06-Huggingface-Endpoints.ipynb
  04-MODEL/assets/06-huggingface-endpoints-dedicated-endpoints-01.png
  04-MODEL/assets/06-huggingface-endpoints-dedicated-endpoints-02.png
  04-MODEL/assets/06-huggingface-endpoints-dedicated-endpoints-03.png
Labels: feature enhancement

#138 [E-1] 01-Basic/05-Using-OpenAIAPI-MultiModal
  01-Basic/05-Using-OpenAIAPI-MultiModal.ipynb
Labels: make a change on existing file

#135 [Docs] draft license / code-of-conduct / readme
  CODE_OF_CONDUCT.md
  LICENCE.txt
  README.md
Labels: proofread

#151 [Docs] update license / code-of-conduct / readme
  CODE_OF_CONDUCT.md
  LICENCE.txt
  README.md
Labels: hot fix

#145 [N-1] 06-DocumentLoader / 06-WordLoader
  06-DocumentLoader/06-WordLoader.ipynb
  06-DocumentLoader/data/sample-word-document_eng.docx
Labels: feature enhancement

#170 [N-3] 08-Embedding / 03-HuggingFaceEmbeddings
  08-Embedding/03-HuggingFaceEmbeddings.ipynb
Labels: proofread

#176 [E-4] 13-LangChain-Expression-Language / 09-Generator
  13-LangChain-Expression-Language/09-Generator.ipynb
Labels: feature enhancement

#179 [N-3] 08-Embedding / 01-OpenAIEmbeddings.ipynb
  08-Embedding/01-OpenAIEmbeddings.ipynb
Labels: proofread

#187 [N-2] 07-Text Splitter / 05-CodeSplitter
  07-TextSplitter/05-CodeSplitter.ipynb
Labels: proofread, hot fix

#146 [E-4] 13-LangChain-Expression-Language / 11-Fallbacks
  13-LangChain-Expression-Language/11-Fallbacks.ipynb
Labels: feature enhancement

#181 [E-4] 13-LangChain-Expression-Language / 01-RunnablePassthrough
  13-LangChain-Expression-Language/01-RunnablePassthrough.ipynb
Labels: feature enhancement

#188 [E-1] 02-Prompt / 02-FewShotPromptTemplate.ipynb
  02-Prompt/02-FewShotPromptTemplate.ipynb
  10-Retriever/06-MultiQueryRetriever.ipynb
Labels: feature enhancement, proofreading

#195 [E-4] 13-LangChain-Expression-Language / 04-Routing
  13-LangChain-Expression-Language/04-Routing.ipynb
Labels: feature enhancement

#206 [E-4] 05-Memory / 06-ConversationSummaryMemory
  05-Memory/06-ConversationSummaryMemory.ipynb
Labels: proofreading

#288 [E-3] 04-MODEL / 01-Models
  04-Model/01-Models.ipynb
Labels: proofreading

#207 [E-2] 03-OutputParser / 02-CommaSeparatedListOutputParser
  13-LangChain-Expression-Language/09-Generator.ipynb
Labels: proofreading

#251 [N-1] 06-Document Loader / 11-UpstageDocumentParseLoader
  06-DocumentLoader/11-UpstageDocumentParseLoader.ipynb
Labels: proofreading, hot fix

#183 [E-2] 11-Reranker / 01-CrossEncoderReranker
  11-Reranker/01-CrossEncoderReranker.ipynb
  11-Reranker/data/appendix-keywords.txt
Labels: feature enhancement

#261 [N-1] 06-DocumentLoader / 10-ArxivLoader
  06-DocumentLoader/10-ArxivLoader.ipynb
Labels: proofreading

#182 [E-1] 1-BASIC / 01-Getting-Started-Windows
  01-Basic/01-Getting-Started-Windows.ipynb
  01-Basic/assets/01-follow-the-installation-video-windows-06.png
  01-Basic/assets/01-follow-the-installation-video-windows-07.png
  01-Basic/assets/01-follow-the-installation-video-windows-08.png
Labels: bug, proofreading

#295 [Template] Add base template with example content removed, including guide
  99-TEMPLATE/00-BASE-TEMPLATE-GUIDE.ipynb
  99-TEMPLATE/00-BASE-TEMPLATE.ipynb
Labels: proofreading, highlight

#287 [E-4] 05-MEMORY/09-MemoryUsingSQLite
  05-Memory/09-Memory-Using-SQLite.ipynb
Labels: proofreading

#278 [N-1] 05-Memory / 08-LCEL-add-memory
  05-Memory/08-LCEL-add-memory.ipynb
Labels: proofreading

#150 [E-1] 10-Retriever / 10-Kiwi-BM25-Retriver
  10-Retriever/10-Kiwi-BM25-Retriever.ipynb
Labels: feature enhancement

#175 [E-1] 10-Retriever / 04-LongContextReorder
  10-Retriever/04-LongContextReorder.ipynb
Labels: feature enhancement

#173 [E-1] 10-Retriever / 01-VectorStoreRetriever
  01-Basic/05-Using-OpenAIAPI-MultiModal.ipynb
  10-Retriever/01-VectorStoreRetriever.ipynb
  10-Retriever/assets/01-vectorstore-retriever-get-upstage-api-key.png
  10-Retriever/assets/01-vectorstore-retriever-rag-flow.png
  10-Retriever/data/01-vectorstore-retriever-appendix-keywords.txt
Labels: feature enhancement

#243 [N-1] 06-Document Loader / 12-LlamaParse.ipynb
  06-DocumentLoader/12-LlamaParse.ipynb
Labels: proofreading

#302 [E-4] 05-MEMORY/05-ConversationKGMemory
  05-Memory/05-ConversationKGMemory.ipynb
Labels: proofreading

#296 [N-1] 06-DocumentLoader / 13-HWPLoader
  06-DocumentLoader/13-HWPLoader.ipynb
Labels: proofreading

#331 [Gitbook] uploading 01-08 revision files
  docs/01-Basic/01-Getting-Started-Windows.md
  docs/01-Basic/05-Using-OpenAIAPI-MultiModal.md
  docs/02-Prompt/02-FewShotPromptTemplate.md
  docs/04-Model/01-Models.md
  docs/05-Memory/05-ConversationKGMemory.md
  docs/05-Memory/06-ConversationSummaryMemory.md
  docs/05-Memory/08-LCEL-add-memory.md
  docs/05-Memory/09-Memory-Using-SQLite.md
  docs/06-DocumentLoader/05-ExcelLoader.md
  docs/06-DocumentLoader/10-ArxivLoader.md
  docs/06-DocumentLoader/11-UpstageDocumentParseLoader.md
  docs/06-DocumentLoader/12-LlamaParse.md
  docs/06-DocumentLoader/13-HWPLoader.md
  docs/08-Embedding/08-MultiModalEmbeddings.md
Labels: GitBook

#289 05-Memory / 04-ConversationEntityMemory
  05-Memory/04-ConversationEntityMemory.ipynb
Labels: proofreading

#343 [E-4] 05-Memory / 07-VectorStoreRetrieverMemory
  05-Memory/07-VectorStoreRetrieverMemory.ipynb
Labels: proofreading

#301 [E-1] 01-Basic / 04-LangSmith-Tracking-Setup
  01-Basic/04-LangSmith-Tracking-Setup.ipynb
Labels: proofreading

#319 [E-2] 03-OutputParser / 01-PydanticOutputParser
  03-OutputParser/01-PydanticOuputParser.ipynb
  03-OutputParser/01-PydanticOutputParser.ipynb
Labels: proofreading

#351 [E-4] 13-LCEL / 07-ChainDecorator
  13-LangChain-Expression-Language/07-ChainDecorator.ipynb
Labels: proofreading

#369 [E-1] 01-BASIC / 01-Follow the Installation Video_Mac
  01-Basic/02-Getting-Started-Mac.ipynb
Labels: proofreading

#354 08-Embedding / 02-CacheBackedEmbeddings
  08-Embedding/02-CacheBackedEmbeddings.ipynb
Labels: proofreading

#337 04-Model / 04-ModelSerialization
  04-Model/04-ModelSerialization.ipynb
Labels: proofreading

#366 [N-1] 06-DocumentLoader / 08-TXT-Loader
  06-DocumentLoader/08-TXTLoader.ipynb
Labels: proofreading

#379 [E-2] 11-Reranker / 01-CrossEncoderReranker
  11-Reranker/01-CrossEncoderReranker.ipynb
Labels: proofreading

#411 [E-1] 10-Retriever / 08-SelfQueryRetriever
  10-Retriever/08-SelfQueryRetriever.ipynb
Labels: proofreading

#362 [E-1] 01-Basic / 03-OpenAIAPI-Key-Generation
  01-Basic/03-OpenAIAPI-Key-Generation.ipynb
Labels: proofreading

#339 [E-2] 03-OutputParser / 06-DatetimeOutputParser
  03-OutputParser/06-DatetimeOutputParser.ipynb
Labels: proofreading

#435 [E-4] 13-LCEL / 03-RunnableLamda
  13-LangChain-Expression-Language/03-RunnableLambda.ipynb
Labels: proofreading

#232 [N-2] 09-VectorStore / 05-Qdrant.ipynb
  09-VectorStore/05-Qdrant.ipynb
Labels: docs, new tutorial suggestions

#270 [N-1] 04-GraphRAG / 07-AcademicSearchSystem
  19-Cookbook/04-GraphRAG/07-AcademicSearchSystem.ipynb
  19-Cookbook/04-GraphRAG/assets/07-academic-search-system-01.png
  19-Cookbook/04-GraphRAG/assets/07-academic-search-system-02.png
  19-Cookbook/04-GraphRAG/assets/07-academic-search-system-03.png
  19-Cookbook/04-GraphRAG/assets/07-academic-search-system-04.png
  19-Cookbook/04-GraphRAG/assets/07-academic-search-system-05.png
Labels: docs, new tutorial suggestions

#310 [N-3] 13-LangChain-Expression-Language / 12-RunnableRetry
  13-LangChain-Expression-Language/12-RunnableRetry.ipynb
Labels: docs, new tutorial suggestions

#371 [E-4] 15-Agent / 09-MakeReport-Using-RAG-Websearching-Imagegeneration…
  15-Agent/09-MakeReport-Using-RAG-Websearching-Imagegeneration-Agent.ipynb
  15-Agent/assets/09-makereport-using-rag-websearching-imagegeneration-report-add-image.png
  15-Agent/assets/09-makereport-using-rag-websearching-imagegeneration-report-summary.png
  15-Agent/assets/09-makereport-using-rag-websearching-imagegeneration-report-using-rag.png
  15-Agent/assets/09-makereport-using-rag-websearching-imagegeneration-report-using-websearching.png
Labels: docs

#375 [E-1] 14-Chains / 03-StructuredOutputChain
  14-Chains/03-Structured-Output-Chain.ipynb
Labels: docs

#384 [E-2] 16-Evaluations / 06-LangSmith-Embedding-Distance-Evaluation
  16-Evaluations/06-LangSmith-Embedding-Distance-Evaluation.ipynb
  16-Evaluations/assets/06-langsmith-embedding-distance-evaluation-01.png
Labels: docs

#425 [N-1] 01-SQL / 02-SpeechToSQL
  19-Cookbook/01-SQL/02-SpeechToSQL.ipynb
Labels: docs, new tutorial suggestions

#264 [N-2] 09-VectorStore / 07-MongoDB-Atlas
  09-VectorStore/07-MongoDB-Atlas.ipynb
  09-VectorStore/assets/07-mongodb-atlas-collection-01.png
  09-VectorStore/assets/07-mongodb-atlas-collection-02.png
  09-VectorStore/assets/07-mongodb-atlas-database.png
  09-VectorStore/assets/07-mongodb-atlas-initialization-01.png
  09-VectorStore/assets/07-mongodb-atlas-initialization-02.png
  09-VectorStore/assets/07-mongodb-atlas-search-index-01.png
  09-VectorStore/assets/07-mongodb-atlas-search-index-02.png
  09-VectorStore/assets/07-mongodb-atlas-search-index-03.png
  09-VectorStore/assets/07-mongodb-atlas-search-index-04.png
Labels: docs, new tutorial suggestions

#426 [N-1] 06-DocumentLoader / 04-CSV-Loader
  06-DocumentLoader/04-CSVLoader.ipynb
Labels: proofreading

#434 [E-4] 05-Memory / 02-ConversationBufferWindowMemory
  05-Memory/02-ConversationBufferWindowMemory.ipynb
Labels: proofreading

#462 [N-2] 07-TextSplitter/03-TokenTextSplitter
  07-TextSplitter/03-TextSplittingMethods_.ipynb
Labels: proofreading

#443 [E-4] 13-LangChain-Expression-Language / 04-Routing 이슈 사항 반영
  13-LangChain-Expression-Language/04-Routing.ipynb
Labels: proofreading

#448 [E-4] 13-LCEL / 10-Binding
  13-LangChain-Expression-Language/10-Binding.ipynb
Labels: proofreading

#455 [E-2] 11-Reranker / 04-FlashRank-Reranker
  11-Reranker/04-FlashRank-Reranker.ipynb
Labels: proofreading

#247 [N-1] 03-GraphDB / 04-MovieQASystem
  19-Cookbook/03-GraphDB/04-MovieQASystem.ipynb
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-basic-workflow.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-chain-flow.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-01.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-02.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-03.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-04.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-05.png
  19-Cookbook/03-GraphDB/assets/04-movie-qa-system-setup-06.png
Labels: docs, new tutorial suggestions

#380 [E-2] 16-Evaluations / 05-LangSmith-LLM-as-Judge
  16-Evaluations/05-LangSmith-LLM-as-Judge.ipynb
  16-Evaluations/assets/05-langsmith-llm-as-judge-01.png
  16-Evaluations/assets/05-langsmith-llm-as-judge-02.png
  16-Evaluations/assets/05-langsmith-llm-as-judge-03.png
  16-Evaluations/assets/05-langsmith-llm-as-judge-04.png
  16-Evaluations/assets/05-langsmith-llm-as-judge-05.png
  16-Evaluations/myrag.py
Labels: docs

#461 [N-2] 07-Text Splitter / 04-SemanticChunker
  07-TextSplitter/04-SemanticChunker.ipynb
Labels: proofreading

#275 [N-2] 09-VectorStore / 04-Pinecone
  09-VectorStore/04-Pinecone.ipynb
  09-VectorStore/assets/04-pinecone-api-01.png
  09-VectorStore/assets/04-pinecone-api-02.png
  09-VectorStore/assets/04-pinecone-filter.png
  09-VectorStore/assets/04-pinecone-index.png
  09-VectorStore/assets/04-pinecone-multimodal-01.png
  09-VectorStore/assets/04-pinecone-multimodal-02.png
  09-VectorStore/assets/04-pinecone-multimodal-03.png
  09-VectorStore/assets/04-pinecone-namespaces-01.png
  09-VectorStore/assets/04-pinecone-namespaces-02.png
  09-VectorStore/assets/04-pinecone-upsert.png
Labels: docs, new tutorial suggestions

#444 [E-4] 05-Memory / 10-Conversation-With-History
  05-Memory/10-Conversation-With-History.ipynb
Labels: proofreading

#441 [E-1] 10-Retriever / 06-MultiQueryRetriever
  10-Retriever/06-MultiQueryRetriever.ipynb
Labels: proofreading

#478 English translation of templates
  99-TEMPLATE/English/00-BASE-TEMPLATE-EXAMPLE.ipynb
  99-TEMPLATE/English/00-BASE-TEMPLATE-GUIDE.ipynb
  99-TEMPLATE/English/assets/langgraph-adaptive-rag.png
  99-TEMPLATE/Korean/00-BASE-TEMPLATE-EXAMPLE.ipynb
  99-TEMPLATE/Korean/00-BASE-TEMPLATE-GUIDE.ipynb
  99-TEMPLATE/Korean/00-BASE-TEMPLATE.ipynb
  99-TEMPLATE/Korean/assets/langgraph-adaptive-rag.png
  README.md
  docs/README.md
Labels: question, proofreading, check plz

#277 [N-3] 13-Langchain-Expression-Language / 04-Routing
  13-LangChain-Expression-Language/04-Routing.ipynb
  13-LangChain-Expression-Language/assets/04-routing-runnable-pipeline.png
Labels: docs, new tutorial suggestions

#482 [E-4] 15-Agent / 02-Bind-Tools
  15-Agent/02-Bind-Tools.ipynb
Labels: proofreading

#481 [E-4] 13-LCEL / 08-RunnableWithMessageHistory
  13-LangChain-Expression-Language/08-RunnableWithMessageHistory.ipynb
Labels: proofreading

#480 [E-4] 13-LCEL / 05-RunnableParallel
  13-LangChain-Expression-Language/05-RunnableParallel.ipynb
Labels: proofreading

#463 docs: update README.md
  README.md
Labels: check plz

#442 E-2] 03-OutputParser / 05- PandasDataFrameOutputParser
  03-OutputParser/05-PandasDataFrameOutputParser.ipynb
Labels: proofreading

#445 Proofread: < 12-RAG /03-RAG-Advanced >
  12-RAG/03-RAG-Advanced.ipynb
Labels: proofreading

#449 [E-4] 13-LangChain-Expression-Language/01-RunnablePassThrough
  13-LangChain-Expression-Language/01-RunnablePassThrough.ipynb
Labels: proofreading

#460 Proofread: < 05-Memory / 01-ConversationBufferMemory >
  05-Memory/01-ConversationBufferMemory.ipynb
Labels: proofreading

#493 [N-1] 06-DocumentLoader / 04-CSV-Loader
  06-DocumentLoader/04-CSVLoader.ipynb
Labels: GitBook

#504 [E-4] 15-Agent / 03-Agent
  15-Agent/03-Agent.ipynb
Labels: proofreading

#496 [E-4] 13-LangChain-Expression-Language / 11-Fallbacks
  13-LangChain-Expression-Language/11-Fallbacks.ipynb
Labels: docs, proofreading

#245 [N-1] 05-AIMemoryManagementSystem / 09-ConversationMemoryManagementSystem
  19-Cookbook/05-AIMemoryManagementSystem/09-ConversationMemoryManagementSystem.ipynb
Labels: docs, new tutorial suggestions

#468 [E-1] 17-LangGraph / 01-Core-Features / 04-LangGraph-Agent-With-Memory
  17-LangGraph/01-Core-Features/04-LangGraph-Agent-With-Memory.ipynb
Labels: docs, proofreading

#500 [E-1] 01-BASIC / 01-Follow the Installation Video_Mac
  01-Basic/02-Getting-Started-Mac.ipynb
Labels: GitBook

#392 [N-3] 17-LangGraph / 01-Core-Features / 16-LangGraph-Errors
  17-LangGraph/01-Core-Features/16-LangGraph-Errors.ipynb
Labels: docs, new tutorial suggestions

#484 [E-4]13-LCEL / 09-Generator
  13-LangChain-Expression-Language/09-Generator.ipynb
Labels: proofreading

#518 13-LangChain-Expression-Language/01-RunnablePassthrough
  13-LangChain-Expression-Language/01-RunnablePassThrough.ipynb
Labels: GitBook

#539 15-Agent/10-TwoAgentDebateWithTools
  15-Agent/10-TwoAgentDebateWithTools.ipynb
Labels: proofreading, GitBook

#479 [N-1] 06-DocumentLoader / 01-DocumentLoader
  06-DocumentLoader/01-DocumentLoader.ipynb
Labels: proofreading

#486 [E-1] 17-LangGraph / 01-Core-Features / 03-LangGraph-Agent
  17-LangGraph/01-Core-Features/03-LangGraph-Agent.ipynb
  17-LangGraph/01-Core-Features/assets/03-langgraph-agent-conditional-edge.png
  17-LangGraph/01-Core-Features/assets/03-langgraph-agent-diagram.png
Labels: docs

#495 [E-4] 17-LangGraph / 03-Use Cases / 02-LangGraph-Prompt-Generation
  17-LangGraph/03-Use-Cases/02-LangGraph-Prompt-Generation.ipynb
  17-LangGraph/03-Use-Cases/assets/02-LangGraph-Prompt-Generation-meta-prompt-generator.png
Labels: docs

#531 [E-3] 17-LangGraph / 02-Structures / 06-LangGraph-Agentic-RAG
  17-LangGraph/02-Structures/06-LangGraph-Agentic-RAG.ipynb
  17-LangGraph/02-Structures/assets/06-langgraph-agentic-rag.png
  17-LangGraph/02-Structures/data/A European Approach to Artificial Intelligence - A Policy Perspective.pdf
Labels: docs

#535 [E-1] 17-LangGraph/01-CoreFeatures/14-LangGraph-Subgraph-Transform-State
  17-LangGraph/01-Core-Features/14-LangGraph-Subgraph-Transform-State.ipynb
Labels: docs

#507 [E-4] 17-LangGraph / 03-Use-Cases / 07-LangGraph-Multi-Agent-Supervisor
  17-LangGraph/03-Use-Cases/07-LangGraph-Multi-Agent-Supervisor.ipynb
  17-LangGraph/03-Use-Cases/assets/07-langgraph-multi-agent-supervisor.png
Labels: docs

#519 [E-3] 17-LangGraph / 02-Structures / 01-LangGraph-Building-Graphs
  17-LangGraph/02-Structures/01-LangGraph-Building-Graphs.ipynb
Labels: docs

#508 [E-2] 17-LangGraph / 01-Core-Features / 15-LangGraph-Streaming-steps
  17-LangGraph/01-Core-Features/15-LangGraph-Streaming-steps.ipynb
Labels: docs

#512 [E-1] 17-LangGraph / 01-Core-Features / 06-LangGraph-Human-in-the-loop
  17-LangGraph/01-Core-Features/06-LangGraph-Human-in-the-loop.ipynb
Labels: docs, proofreading

#514 [E-2] 17-LangGraph / 01-Core-Features / 13-LangGraph-Subgraph
  17-LangGraph/01-Core-Features/13-LangGraph-Subgraph.ipynb
  17-LangGraph/01-Core-Features/assets/13-langgraph-subgraph.png
Labels: docs

#534 [E-4] 17-LangGraph/03-Use-Cases/01-LangGraph-Agent-Simulation
  17-LangGraph/03-Use-Cases/01-LangGraph-Agent-Simulation.ipynb
  17-LangGraph/03-Use-Cases/assets/01-langgraph-agent-simulation.png
Labels: docs

#547 [E-4] 17-LangGraph / 03-Use-Cases / 06-Multi-Agent-Collaboration
  17-LangGraph/03-Use-Cases/06-Multi-Agent-Collaboration.ipynb
  17-LangGraph/03-Use-Cases/assets/17-langgraph-multi-agent-network.png
Labels: docs, proofreading

#530 [E-4] 17-LangGraph / 03-Use-Cases / 10-LangGraph-Research-Assistant
  17-LangGraph/03-Use-Cases/10-LangGraph-Research-Assistant.ipynb
  17-LangGraph/03-Use-Cases/assets/10-LangGraph-Research-Assitant-concept.png
Labels: docs, proofreading

#472 [E-1] 17-LangGraph / 01-Core-Features / 08-LangGraph-State-Customization
  17-LangGraph/01-Core-Features/08-LangGraph-State-Customization.ipynb
  17-LangGraph/01-Core-Features/assets/08-langgraph-state-customization.png
Labels: docs

#516 [E-3] 17-LangGraph / 02-Structures / 02-LangGraph-Naive-RAG
  17-LangGraph/02-Structures/02-LangGraph-Naive-RAG.ipynb
  17-LangGraph/02-Structures/assets/02-langgraph-naive-rag.png
Labels: docs

#499 [E-1] 17-LangGraph / 01-Core-Features / 01-LangGraph-Introduction
  17-LangGraph/01-Core-Features/01-LangGraph-Introduction.ipynb
Labels: docs, proofreading

#515 [E-2] 17-LangGraph / 01-Core-Features / 11-LangGraph-Branching
  17-LangGraph/01-Core-Features/11-LangGraph-Branching.ipynb
  17-LangGraph/01-Core-Features/assets/11-langgraph-branching-graph.png
Labels: docs, proofreading

#537 [E-4] 17-LangGraph / 03-Use-Cases / 05_LangGraph_Plan_and_Execute
  17-LangGraph/03-Use-Cases/05_LangGraph_Plan_and_Execute.ipynb
  17-LangGraph/03-Use-Cases/assets/05-langgraph-plan-and-execute.png
Labels: docs, proofreading
