Repository LangChain-OpenTutorial/LangChain-OpenTutorial, pull requests merged in 2025-02, with the labels that each got.

#572 [E-2] 17-LangGraph/01-Core-Features /10-LnagGraph-ToolNode
  17-LangGraph/01-Core-Features/10-LnagGraph-ToolNode.ipynb
Labels: proofreading

#569 [E-2] 17-LangGraph / 09-DeleteMessages
  17-LangGraph/01-Core-Features/09-DeleteMessages.ipynb
Labels: proofreading

#575 [E-1] 14-Chains / 03-StructuredOutputChain
  14-Chains/03-Structured-Output-Chain.ipynb
Labels: proofreading

#567 [E-4] 15-Agent / 04-Agent-More-LLMs
  15-Agent/04-Agent-More-LLMs.ipynb
Labels: proofreading

#555 [E-1] 14-Chains / 04-Structured-Data-Chat
  14-Chains/04-Structured-Data-Chat.ipynb
Labels: proofreading

#549 [E-1] 14-Chains / 02-SQL
  14-Chains/02-SQL.ipynb
Labels: proofreading

#542 [N-1] / [06-DocumentLoader]/09-JSONLoader
  06-DocumentLoader/09-JSONLoader.ipynb
Labels: proofreading

#541 [N-3] / [17-LangGraph]/ 16-LangGraph-SemanticSearch
  06-DocumentLoader/09-JSONLoader.ipynb
Labels: new tutorial suggestions

#509 [E-1] 10-Retriever / 10-Kiwi-BM25-Retriever #415
  10-Retriever/10-Kiwi-BM25-Retriever.ipynb
Labels: proofreading

#483 [E-2] 17-LangGraph / 01-Core-Features / 12-Conversation-Summaries-with-LangGraph
  17-LangGraph/01-Core-Features/12-Conversation-Summaries-with-LangGraph.ipynb
  17-LangGraph/01-Core-Features/assets/12-conversation-summaries-with-langgraph_visualize.png
Labels: docs, proofreading

#469 [E-1] 17-LangGraph / 01-Core-Features / 02-LangGraph-ChatBot
  17-LangGraph/01-Core-Features/02-LangGraph-ChatBot.ipynb
Labels: docs, proofreading

#488 [E-3] 17-LangGraph/02-Structures/LangGraph-Add-Query-Rewrite
  17-LangGraph/02-Structures/05-LangGraph-Add-Query-Rewrite.ipynb
  17-LangGraph/02-Structures/assets/05-langgraph-add-query-rewrite-01.png
Labels: docs, proofreading

#587 [N-1] 06-DocumentLoader / 02-PDFLoader
  06-DocumentLoader/02-PDFLoader.ipynb
Labels: proofreading

#490 [E-4] 17-LangGraph / 03-Use-Cases / 08-Hierarchical-Multi-Agent-Teams
  17-LangGraph/03-Use-Cases/08-Hierarchical-Multi-Agent-Teams.ipynb
Labels: docs

#546 Proofread: < 16-Evaluations / 02-Evaluation-using-RAGAS >
  16-Evaluations/02-Evaluation-using-RAGAS.ipynb
Labels: proofreading

#485 [E-2] 16-Evaluations / 04-LangSmith-Dataset
  16-Evaluations/04-LangSmith-Dataset.ipynb
  16-Evaluations/assets/04-langsmith-dataset-01.png
  16-Evaluations/assets/04-langsmith-dataset-02.png
  16-Evaluations/assets/04-langsmith-dataset-03.png
Labels: docs

#524 [E-4] 17-LangGraph / 03-Use-Cases / 03-LangGraph-CRAG
  17-LangGraph/03-Use-Cases/03-LangGraph-CRAG.ipynb
  17-LangGraph/03-Use-Cases/assets/03-Langgraph-CRAG.png
Labels: docs

#621 [E-1] 10-Retriever / 11-Convex-Combination-Ensemble-Retriever
  10-Retriever/11-Convex-Combination-Ensemble-Retriever.ipynb
Labels: proofreading

#494 [E-1] 17-LangGraph / 01-Core-Features / 07-LangGraph-Manual-State-Update
  17-LangGraph/01-Core-Features/07-LangGraph-Manual-State-Update.ipynb
  17-LangGraph/01-Core-Features/assets/07-langgraph-manual-state-update.png
Labels: docs

#568 [N-1] 07-Agent / 19-NewEmployeeOnboardingChatbot
  19-Cookbook/07-Agent/19-NewEmployeeOnboardingChatbot.ipynb
Labels: new tutorial suggestions

#523 [E-3] 17-LangGraph / 02-Structures / 04-LangGraph-Add-Web-Search
  17-LangGraph/02-Structures/04-LangGraph-Add-Web-Search.ipynb
  17-LangGraph/02-Structures/assets/04-langgraph-add-web-search-langgraph-web-search.png
  17-LangGraph/02-Structures/rag/__init__.py
  17-LangGraph/02-Structures/rag/base.py
  17-LangGraph/02-Structures/rag/evaluator.py
  17-LangGraph/02-Structures/rag/graphs.py
  17-LangGraph/02-Structures/rag/messages.py
  17-LangGraph/02-Structures/rag/tavily.py
  17-LangGraph/02-Structures/rag/utils.py
Labels: docs, proofreading

#637 [E-1] 17-LangGraph / 01-Core-Features / 01-LangGraph-Introduction
  17-LangGraph/01-Core-Features/01-LangGraph-Introduction.ipynb
Labels: proofreading

#586 [E-3] 17-LangGraph / 02-Structures / 07-Adaptive-Rag
  17-LangGraph/02-Structures/07-Adaptive-Rag.ipynb
  17-LangGraph/02-Structures/assets/07-langgraph-adaptive-rag-01.png.png
  17-LangGraph/02-Structures/assets/07-langgraph-adaptive-rag-02.png
Labels: docs

#394 [E-1] 12-RAG / 10-Multi_modal_RAG-GPT-4o
  12-RAG/10-Multi_modal_RAG-GPT-4o.ipynb
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-01.png
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-02.png
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-03.png
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-04.png
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-05.png
  12-RAG/assets/10-multi_modal_rag-gpt-4o-graphic-06.png
  12-RAG/data/sample.pdf
Labels: docs

#489 [N-1] 07-Agent / 16-Multi-AgentShoppingMallSystem
  19-Cookbook/07-Agent/16-MultiAgentShoppingMallSystem.ipynb
  19-Cookbook/07-Agent/assets/16-multi-agent-shopping-mall-system-01.png
  19-Cookbook/07-Agent/assets/16-multi-agent-shopping-mall-system-02.png
  19-Cookbook/07-Agent/assets/16-multi-agent-shopping-mall-system-03.png
  19-Cookbook/07-Agent/assets/16-multi-agent-shopping-mall-system-04.png
Labels: new tutorial suggestions

#563 07-Textsplitter / 02-RecursiveCharacterTextSplitter
  07-TextSplitter/02-RecursiveCharacterTextSplitter.ipynb
Labels: proofreading

#594 [E-3] 04-Model / 07-Huggingface-Endpoints
  04-Model/07-Huggingface-Endpoints.ipynb
Labels: proofreading

#598 [E-4] 17-LangGraph / 03-Use-Cases / 09-SQL-Agent
  17-LangGraph/03-Use-Cases/09-SQL-Agent.ipynb
  17-LangGraph/03-Use-Cases/assets/09-sql-agent-evaluation-results.png
  17-LangGraph/03-Use-Cases/assets/09-sql-agent-work-flow.png
Labels: docs, proofreading

#619 [E-2] 16-Evaluations / 05-LangSmith-LLM-as-Judge
  16-Evaluations/05-LangSmith-LLM-as-Judge.ipynb
Labels: proofreading

#620 [N-3] 15-Agent / 05-Iteration-HumanInTheLoop
  15-Agent/05-Iteration-HumanInTheLoop.ipynb
Labels: proofreading

#684 03-OutputParser / 02-CommaSeparatedListOutputParser
  03-OutputParser/02-CommaSeparatedListOutputParser.ipynb
Labels: proofreading

#662 [E-1] 17-LangGraph / 01-Core-Features / 06-LangGraph-Human-in-the-loop
  17-LangGraph/01-Core-Features/06-LangGraph-Human-in-the-loop.ipynb
Labels: docs

#641 16-Evaluations / 04-LangSmith-Dataset
  16-Evaluations/04-LangSmith-Dataset.ipynb
Labels: proofreading

#692 17-LangGraph / 02-Structures / 05-LangGraph-Add-Query-Rewrite.ipynb
  17-LangGraph/02-Structures/05-LangGraph-Add-Query-Rewrite.ipynb
Labels: proofreading

#639 Update 01-Tools.ipynb
  15-Agent/01-Tools.ipynb
Labels: proofreading

#676 Proofread: < 03-OutputParser / 04-JsonOutputParser >
  03-OutputParser/04-JsonOutputParser.ipynb
Labels: proofreading

#679 [E-1] 02-PROMPT / 01-Prompt Template
  02-Prompt/01-PromptTemplate.ipynb
Labels: proofreading

#630 [E-4] 15-Agent / 06-Agentic-RAG
  15-Agent/06-Agentic-RAG.ipynb
Labels: proofreading

#640 15-Agent / 09-MakeReport-Using-RAG-Websearching-Imagegeneration-Agent
  15-Agent/09-MakeReport-Using-RAG-Websearching-Imagegeneration-Agent.ipynb
Labels: proofreading

#654 [E-4] 15-Agent / 07-CSV-Excel-Agent
  15-Agent/07-CSV-Excel-Agent.ipynb
Labels: proofreading

#659 [N-1] 06-DocumentLoader / 01-DocumentLoader
  06-DocumentLoader/01-DocumentLoader.ipynb
Labels: docs

#702 [Proofread] 03 - Output Parsers / 03-StructuredOutputParser
  03-OutputParser/03-StructuredOutputParser.ipynb
Labels: proofreading

#686 [E-4] 15-Agent / 08-Agent-with-Toolkits-File-Management
  15-Agent/08-Agent-with-Toolkits-File-Management.ipynb
Labels: proofreading

#726 Proofread: 02-Prompt / 05-Prompt-Caching
  02-Prompt/05-Prompt-Caching.ipynb
Labels: proofreading

#649 Proofread: <16-Evaluations / 03-HF-Upload >
  16-Evaluations/03-HF-Upload.ipynb
Labels: proofreading

#694 Proofread: < 16-Evaluations/01-GenerateSyntheticTestDataset >
  16-Evaluations/01-GenerateSyntheticTestDataset.ipynb
Labels: proofreading

#688 Proofread: 04-Model / 02-Chat-Models
  04-Model/02-Chat-Models.ipynb
Labels: proofreading

#761 Proofread: 16-Evaluations / 06-LangSmith-Embedding-Distance-Evaluations
  16-Evaluations/06-LangSmith-Embedding-Distance-Evaluation.ipynb
Labels: proofreading

#781 Proofread: 06-DocumentLoader / 06-WordLoader
  06-DocumentLoader/06-WordLoader.ipynb
Labels: proofreading

#653 12-RAG / 05-Conversation-With-History.ipynb
  12-RAG/05-Conversation-With-History.ipynb
Labels: proofreading

#743 [proofread] 19-Cookbook/07-Agent/19-NewEmployeeOnboardingChatbot.ipynb
  19-Cookbook/07-Agent/19-NewEmployeeOnboardingChatbot.ipynb
Labels: proofreading

#755 Proofread: 06-DocumentLoader / 05-ExcelLoader
  06-DocumentLoader/05-ExcelLoader.ipynb
Labels: proofreading

#764 Proofread: 16-Evaluations / 09-CompareEvaluation
  16-Evaluations/09-CompareEvaluation.ipynb
Labels: proofreading

#775 Proofread: 06-DocumentLoader / 02-PDFLoader
  06-DocumentLoader/02-PDFLoader.ipynb
Labels: proofreading

#785 Proofread: 13-LangChain-Expression-Language / 01-RunnablePassThrough
  13-LangChain-Expression-Language/01-RunnablePassThrough.ipynb
Labels: proofreading
